/*
Svix API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DataAnyOf4 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DataAnyOf4{}

// DataAnyOf4 struct for DataAnyOf4
type DataAnyOf4 struct {
	MessagesPurged int32 `json:"messages_purged"`
}

type _DataAnyOf4 DataAnyOf4

// NewDataAnyOf4 instantiates a new DataAnyOf4 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDataAnyOf4(messagesPurged int32) *DataAnyOf4 {
	this := DataAnyOf4{}
	this.MessagesPurged = messagesPurged
	return &this
}

// NewDataAnyOf4WithDefaults instantiates a new DataAnyOf4 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDataAnyOf4WithDefaults() *DataAnyOf4 {
	this := DataAnyOf4{}
	return &this
}

// GetMessagesPurged returns the MessagesPurged field value
func (o *DataAnyOf4) GetMessagesPurged() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MessagesPurged
}

// GetMessagesPurgedOk returns a tuple with the MessagesPurged field value
// and a boolean to check if the value has been set.
func (o *DataAnyOf4) GetMessagesPurgedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MessagesPurged, true
}

// SetMessagesPurged sets field value
func (o *DataAnyOf4) SetMessagesPurged(v int32) {
	o.MessagesPurged = v
}

func (o DataAnyOf4) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DataAnyOf4) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["messages_purged"] = o.MessagesPurged
	return toSerialize, nil
}

func (o *DataAnyOf4) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"messages_purged",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDataAnyOf4 := _DataAnyOf4{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDataAnyOf4)

	if err != nil {
		return err
	}

	*o = DataAnyOf4(varDataAnyOf4)

	return err
}

type NullableDataAnyOf4 struct {
	value *DataAnyOf4
	isSet bool
}

func (v NullableDataAnyOf4) Get() *DataAnyOf4 {
	return v.value
}

func (v *NullableDataAnyOf4) Set(val *DataAnyOf4) {
	v.value = val
	v.isSet = true
}

func (v NullableDataAnyOf4) IsSet() bool {
	return v.isSet
}

func (v *NullableDataAnyOf4) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDataAnyOf4(val *DataAnyOf4) *NullableDataAnyOf4 {
	return &NullableDataAnyOf4{value: val, isSet: true}
}

func (v NullableDataAnyOf4) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDataAnyOf4) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


