/*
Svix API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PurgeContentOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PurgeContentOut{}

// PurgeContentOut struct for PurgeContentOut
type PurgeContentOut struct {
	// The QueueBackgroundTask's ID.
	Id string `json:"id" validate:"regexp=^qtask_[A-Za-z0-9]{27}$"`
	Status BackgroundTaskStatus `json:"status"`
	Task BackgroundTaskType `json:"task"`
}

type _PurgeContentOut PurgeContentOut

// NewPurgeContentOut instantiates a new PurgeContentOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPurgeContentOut(id string, status BackgroundTaskStatus, task BackgroundTaskType) *PurgeContentOut {
	this := PurgeContentOut{}
	this.Id = id
	this.Status = status
	this.Task = task
	return &this
}

// NewPurgeContentOutWithDefaults instantiates a new PurgeContentOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPurgeContentOutWithDefaults() *PurgeContentOut {
	this := PurgeContentOut{}
	return &this
}

// GetId returns the Id field value
func (o *PurgeContentOut) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PurgeContentOut) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PurgeContentOut) SetId(v string) {
	o.Id = v
}

// GetStatus returns the Status field value
func (o *PurgeContentOut) GetStatus() BackgroundTaskStatus {
	if o == nil {
		var ret BackgroundTaskStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *PurgeContentOut) GetStatusOk() (*BackgroundTaskStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *PurgeContentOut) SetStatus(v BackgroundTaskStatus) {
	o.Status = v
}

// GetTask returns the Task field value
func (o *PurgeContentOut) GetTask() BackgroundTaskType {
	if o == nil {
		var ret BackgroundTaskType
		return ret
	}

	return o.Task
}

// GetTaskOk returns a tuple with the Task field value
// and a boolean to check if the value has been set.
func (o *PurgeContentOut) GetTaskOk() (*BackgroundTaskType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Task, true
}

// SetTask sets field value
func (o *PurgeContentOut) SetTask(v BackgroundTaskType) {
	o.Task = v
}

func (o PurgeContentOut) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PurgeContentOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["status"] = o.Status
	toSerialize["task"] = o.Task
	return toSerialize, nil
}

func (o *PurgeContentOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"status",
		"task",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPurgeContentOut := _PurgeContentOut{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPurgeContentOut)

	if err != nil {
		return err
	}

	*o = PurgeContentOut(varPurgeContentOut)

	return err
}

type NullablePurgeContentOut struct {
	value *PurgeContentOut
	isSet bool
}

func (v NullablePurgeContentOut) Get() *PurgeContentOut {
	return v.value
}

func (v *NullablePurgeContentOut) Set(val *PurgeContentOut) {
	v.value = val
	v.isSet = true
}

func (v NullablePurgeContentOut) IsSet() bool {
	return v.isSet
}

func (v *NullablePurgeContentOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePurgeContentOut(val *PurgeContentOut) *NullablePurgeContentOut {
	return &NullablePurgeContentOut{value: val, isSet: true}
}

func (v NullablePurgeContentOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePurgeContentOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


