/*
Svix API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MessagePrecheckIn type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MessagePrecheckIn{}

// MessagePrecheckIn struct for MessagePrecheckIn
type MessagePrecheckIn struct {
	Channels []string `json:"channels,omitempty"`
	// The event type's name
	EventType string `json:"eventType" validate:"regexp=^[a-zA-Z0-9\\\\-_.]+$"`
}

type _MessagePrecheckIn MessagePrecheckIn

// NewMessagePrecheckIn instantiates a new MessagePrecheckIn object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMessagePrecheckIn(eventType string) *MessagePrecheckIn {
	this := MessagePrecheckIn{}
	this.EventType = eventType
	return &this
}

// NewMessagePrecheckInWithDefaults instantiates a new MessagePrecheckIn object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMessagePrecheckInWithDefaults() *MessagePrecheckIn {
	this := MessagePrecheckIn{}
	return &this
}

// GetChannels returns the Channels field value if set, zero value otherwise.
func (o *MessagePrecheckIn) GetChannels() []string {
	if o == nil || IsNil(o.Channels) {
		var ret []string
		return ret
	}
	return o.Channels
}

// GetChannelsOk returns a tuple with the Channels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessagePrecheckIn) GetChannelsOk() ([]string, bool) {
	if o == nil || IsNil(o.Channels) {
		return nil, false
	}
	return o.Channels, true
}

// HasChannels returns a boolean if a field has been set.
func (o *MessagePrecheckIn) HasChannels() bool {
	if o != nil && !IsNil(o.Channels) {
		return true
	}

	return false
}

// SetChannels gets a reference to the given []string and assigns it to the Channels field.
func (o *MessagePrecheckIn) SetChannels(v []string) {
	o.Channels = v
}

// GetEventType returns the EventType field value
func (o *MessagePrecheckIn) GetEventType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventType
}

// GetEventTypeOk returns a tuple with the EventType field value
// and a boolean to check if the value has been set.
func (o *MessagePrecheckIn) GetEventTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventType, true
}

// SetEventType sets field value
func (o *MessagePrecheckIn) SetEventType(v string) {
	o.EventType = v
}

func (o MessagePrecheckIn) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MessagePrecheckIn) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Channels) {
		toSerialize["channels"] = o.Channels
	}
	toSerialize["eventType"] = o.EventType
	return toSerialize, nil
}

func (o *MessagePrecheckIn) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"eventType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMessagePrecheckIn := _MessagePrecheckIn{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMessagePrecheckIn)

	if err != nil {
		return err
	}

	*o = MessagePrecheckIn(varMessagePrecheckIn)

	return err
}

type NullableMessagePrecheckIn struct {
	value *MessagePrecheckIn
	isSet bool
}

func (v NullableMessagePrecheckIn) Get() *MessagePrecheckIn {
	return v.value
}

func (v *NullableMessagePrecheckIn) Set(val *MessagePrecheckIn) {
	v.value = val
	v.isSet = true
}

func (v NullableMessagePrecheckIn) IsSet() bool {
	return v.isSet
}

func (v *NullableMessagePrecheckIn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMessagePrecheckIn(val *MessagePrecheckIn) *NullableMessagePrecheckIn {
	return &NullableMessagePrecheckIn{value: val, isSet: true}
}

func (v NullableMessagePrecheckIn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMessagePrecheckIn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


