/*
Svix API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the EndpointMtlsConfigOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EndpointMtlsConfigOut{}

// EndpointMtlsConfigOut struct for EndpointMtlsConfigOut
type EndpointMtlsConfigOut struct {
	ServerCaCert *string `json:"serverCaCert,omitempty"`
}

// NewEndpointMtlsConfigOut instantiates a new EndpointMtlsConfigOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEndpointMtlsConfigOut() *EndpointMtlsConfigOut {
	this := EndpointMtlsConfigOut{}
	return &this
}

// NewEndpointMtlsConfigOutWithDefaults instantiates a new EndpointMtlsConfigOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEndpointMtlsConfigOutWithDefaults() *EndpointMtlsConfigOut {
	this := EndpointMtlsConfigOut{}
	return &this
}

// GetServerCaCert returns the ServerCaCert field value if set, zero value otherwise.
func (o *EndpointMtlsConfigOut) GetServerCaCert() string {
	if o == nil || IsNil(o.ServerCaCert) {
		var ret string
		return ret
	}
	return *o.ServerCaCert
}

// GetServerCaCertOk returns a tuple with the ServerCaCert field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointMtlsConfigOut) GetServerCaCertOk() (*string, bool) {
	if o == nil || IsNil(o.ServerCaCert) {
		return nil, false
	}
	return o.ServerCaCert, true
}

// HasServerCaCert returns a boolean if a field has been set.
func (o *EndpointMtlsConfigOut) HasServerCaCert() bool {
	if o != nil && !IsNil(o.ServerCaCert) {
		return true
	}

	return false
}

// SetServerCaCert gets a reference to the given string and assigns it to the ServerCaCert field.
func (o *EndpointMtlsConfigOut) SetServerCaCert(v string) {
	o.ServerCaCert = &v
}

func (o EndpointMtlsConfigOut) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EndpointMtlsConfigOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ServerCaCert) {
		toSerialize["serverCaCert"] = o.ServerCaCert
	}
	return toSerialize, nil
}

type NullableEndpointMtlsConfigOut struct {
	value *EndpointMtlsConfigOut
	isSet bool
}

func (v NullableEndpointMtlsConfigOut) Get() *EndpointMtlsConfigOut {
	return v.value
}

func (v *NullableEndpointMtlsConfigOut) Set(val *EndpointMtlsConfigOut) {
	v.value = val
	v.isSet = true
}

func (v NullableEndpointMtlsConfigOut) IsSet() bool {
	return v.isSet
}

func (v *NullableEndpointMtlsConfigOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEndpointMtlsConfigOut(val *EndpointMtlsConfigOut) *NullableEndpointMtlsConfigOut {
	return &NullableEndpointMtlsConfigOut{value: val, isSet: true}
}

func (v NullableEndpointMtlsConfigOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEndpointMtlsConfigOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


