[workspace]
members = [
    "generic-queue",
    "svix-webhook-bridge-types",
    "svix-webhook-bridge",
    "svix-webhook-bridge-plugin-queue-consumer",
    "svix-webhook-bridge-plugin-webhook-receiver",
]
