version: "3.7"
services:
  postgres:
    image: postgres:13.4
    command: postgres -c 'max_connections=500'
    volumes:
      - "postgres-data:/var/lib/postgresql/data/"
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  pgbouncer:
    image: edoburu/pgbouncer:1.15.0
    healthcheck:
      test: "pg_isready -h localhost"
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      DB_HOST: "postgres"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      MAX_CLIENT_CONN: 500
    depends_on:
    - postgres

  redis:
    image: "redis:7-alpine"
    # Enable persistence
    command: "--save 60 500 --appendonly yes --appendfsync everysec"
    volumes:
      - "redis-data:/data"
    ports:
      - "6379:6379"

volumes:
  postgres-data:
  redis-data:
