name: Server Release

on:
  release:
    types: [published]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            os: windows-latest

          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest

          - target: x86_64-apple-darwin
            os: macos-latest

          - target: aarch64-apple-darwin
            os: macos-latest
    steps:
      - uses: actions/checkout@master

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          target: ${{ matrix.target }}

      - name: Install musl for x86_64-unknown-linux-musl
        if: ${{ matrix.target == 'x86_64-unknown-linux-musl' }}
        run: sudo apt-get install -y musl-dev musl-tools

      - name: Compile server
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target ${{ matrix.target }} --release --manifest-path server/svix-server/Cargo.toml

      - name: Set environment variables for aarch64 MacOS
        if: ${{ matrix.target == 'aarch64-apple-darwin' }}
        run: echo SDKROOT="$(xcrun -sdk macosx11.1 --show-sdk-path)" >> "$GITHUB_ENV" && \
             echo MACOSX_DEPLOYMENT_TARGET="$(xcrun -sdk macosx11.1 --show-sdk-platform-version)" >> "$GITHUB_ENV"

      - name: Release
        uses: actions/upload-artifact@v3
        with:
          name: svix-server-${{ matrix.target }}
          path: server/target/release/svix-server*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
